### PR TITLE
feat(deps): upgrade Foundry and Circuit UI

### PR DESCRIPTION
**Pull request by felixjung**
Addresses [TL-122](https://sumupteam.atlassian.net/browse/TL-122).

This PR upgrades Foundry to version 3.0.0 and Circuit to version 2.0.0, addressing any breaking changes in those dependencies and links to documentation in the README.

### CODE REVIEW

**Review by connor-baer — APPROVED** [review]
Thank you for these updates! 🙌

I was thinking of turning this project into a [custom template for CRA](https://create-react-app.dev/docs/custom-templates). What do you think of that idea?

**Comment by connor-baer** [comment]
Also, when you merge this, please mark it as a breaking change so that it's released as a new major version.

**Comment by felixjung** [comment]
Template sounds cool. Didn't know they had that nowadays. Also just realized that the `create-component` script is not set up right. Will fix that.

**Comment by herberthenrique** [comment]
What are we missing to merge this? 🤔 
cc @felixjung

**Comment by felixjung** [comment]
I need to fix the `create-component` script. Sorry. Will do so today.

**Comment by felixjung** [comment]
This is turning out more difficult than I had hoped. We install `create-react-app` at latest. The new version uses React 17, which is not compatible with Emotion 10's `jsx` transform (https://github.com/emotion-js/emotion/pull/1970). I tried an older version, but that also has React 17. Will need to investigate this further. We'd need to explicitly configure the non-automatic runtime for React. Haven't investigated how to do that, yet.

**Comment by connor-baer** [comment]
@felixjung Emotion 10 now supports the new `jsx` transforms (here are the [docs](https://5faaafd0bd0f3f0008469537--emotion.netlify.app/docs/css-prop#jsx-pragma)). When you have time, would you mind taking another look at this, please? 🙏

**Comment by felixjung** [comment]
Yes, will do. Already use them on my personal website. 🙃

**Comment by felixjung** [comment]
Closing in favor of #26.

**Pull request closed without merging**
